version: '3.3'

services:

  gateway:
    image: nginx:1.23.1
    network_mode: host
    env_file:
      - port_host.env
    volumes:
      - ./static:/var/www/static
      - ./gateway.nginx:/etc/nginx/conf.d/gateway.conf
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ../certbot/conf:/etc/letsencrypt
      - ../certbot/www:/var/www/certbot
    logging:
      driver: "json-file"
      options:
        max-size: 256m

#  certbot:
#    image: certbot/certbot
#    container_name: certbot
#    volumes:
#      - ../certbot/conf:/etc/letsencrypt
#      - ../certbot/www:/var/www/certbot
#    entrypoint: "/bin/bash -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
#    logging:
#      driver: "json-file"
#      options:
#        tag: "{{.ImageName}}|{{.Name}}"
#        max-size: 256m
