version: '3.3'

services:

  gateway:
    image: nginx:1.19.6
    network_mode: host
    env_file:
      - port_host.env
    volumes:
      - ./static:/var/www/static
      - ./gateway.nginx:/etc/nginx/conf.d/conf.nginx
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./start-nginx.sh:/etc/nginx/start-nginx.sh
      - ../certbot/conf:/etc/letsencrypt
      - ../certbot/www:/var/www/certbot
    command: /bin/bash -c  "chmod +x /etc/nginx/*.sh && /etc/nginx/start-nginx.sh"
    logging:
      driver: "json-file"
      options:
        max-size: 256m

#  certbot:
#    image: certbot/certbot
#    container_name: certbot
#    volumes:
#      - ../certbot/conf:/etc/letsencrypt
#      - ../certbot/www:/var/www/certbot
#    entrypoint: "/bin/bash -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
#    logging:
#      driver: "json-file"
#      options:
#        tag: "{{.ImageName}}|{{.Name}}"
#        max-size: 256m